### ISSUE TITLE
GL React Native finished with non-zero or 2

### ISSUE THREAD

**Issue by l-pa** [ProjectSeptemberInc/gl-react-native#156]
I'am using react-native with gl-react-native module, but when I use command react-native run-android I get this

```
.
.
.
make: *** [C:\Users\user\Documents\GitHub\reactnative-gl-camera\node_modules\gl-react-native\android\build\tmp\buildEXGLLib/local/armeabi-v7a/objs/exgl/__/__/__/__/cpp/EXJSConvertTypedArray.o] Error 2
:RNGL:buildEXGLLib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':RNGL:buildEXGLLib'.
> Process 'command 'C:\Users\user\AppData\Local\Android\sdk\ndk-bundle\ndk-build.cmd'' finished with non-zero exit value 2
```
I added NDK to system variable, so it's working, updated NDK via Android Studio, latest version.

**Comment by gre** [comment]
Hi,
you seem to report a problem with the v3 alpha ( which is on https://github.com/gre/gl-react ) but this repository only track the v2.

I have not tested on windows yet. is there any more explicit errors that this?

**Comment by Delfyn** [comment]
There was, but I fixed them, so I'll put this to gl-react issues :)

**Comment by JustinFincher** [comment]
@Delfyn Hi, glad to see that you fixed these errors, can I ask how do you fix these?
I am using the v3 alpha, and I got errors like:
```
:gl-react-native:downloadJSCHeaders
Download https://raw.githubusercontent.com/WebKit/webkit/38b15a3ba3c1b0798f2036f7cea36ffdc096202e/Source/JavaScriptCore/API/JavaScript.h
Download https://raw.githubusercontent.com/WebKit/webkit/38b15a3ba3c1b0798f2036f7cea36ffdc096202e/Source/JavaScriptCore/API/JSBase.h
Download https://raw.githubusercontent.com/WebKit/webkit/38b15a3ba3c1b0798f2036f7cea36ffdc096202e/Source/JavaScriptCore/API/JSContextRef.h
Download https://raw.githubusercontent.com/WebKit/webkit/38b15a3ba3c1b0798f2036f7cea36ffdc096202e/Source/JavaScriptCore/API/JSObjectRef.h
Download https://raw.githubusercontent.com/WebKit/webkit/38b15a3ba3c1b0798f2036f7cea36ffdc096202e/Source/JavaScriptCore/API/JSRetainPtr.h
Download https://raw.githubusercontent.com/WebKit/webkit/38b15a3ba3c1b0798f2036f7cea36ffdc096202e/Source/JavaScriptCore/API/JSStringRef.h
Download https://raw.githubusercontent.com/WebKit/webkit/38b15a3ba3c1b0798f2036f7cea36ffdc096202e/Source/JavaScriptCore/API/JSValueRef.h
Download https://raw.githubusercontent.com/WebKit/webkit/38b15a3ba3c1b0798f2036f7cea36ffdc096202e/Source/JavaScriptCore/API/WebKitAvailability.h
:gl-react-native:prepareJSC
:gl-react-native:buildEXGLLib
Android NDK: android-9 is unsupported. Using minimum supported version android-14.
make: Entering directory `/Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/src/main/jni'
[armeabi-v7a] Compile        : exgl <= EXGL.c
[armeabi-v7a] Compile        : exgl <= GLImages.c
make: /Users/fincher/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc: Command not found
make: *** [/Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/build/tmp/buildEXGLLib/local/armeabi-v7a/objs/exgl/EXGL.o] Error 127
make: *** Waiting for unfinished jobs....
make: /Users/fincher/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc: Command not found
make: *** [/Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/build/tmp/buildEXGLLib/local/armeabi-v7a/objs/exgl/GLImages.o] Error 127
make: Leaving directory `/Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/src/main/jni'
:gl-react-native:buildEXGLLib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gl-react-native:buildEXGLLib'.
> Process 'command '/Users/fincher/Library/Android/sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by JustinFincher** [comment]
**Update:**
I checked my `sdk/ndk-bundle/toolchains/` foder, which have no `arm-linux-androideabi-4.8` but `arm-linux-androideabi-4.9`.  
I am not familar with Android development, so I am just guessing that the gradle file have some issue with this, like maybe  `commandLine getNdkBuildFullPath()` returns 4.8 but I don't know why.  

**Update:**
Well after some searching I edited `Application.mk` and changed NDK_TOOLCHAIN_VERSION to 4.9, and I got NDK up running. But there are compiling errors:

```
[armeabi-v7a] Compile thumb  : exgl <= GLImages.c
./GLImages.c: In function 'Java_fr_greweb_rngl_GLImages_set':
./GLImages.c:18:3: warning: implicit declaration of function 'memcpy' [-Wimplicit-function-declaration]
   memcpy(data, bitmapPixels, size);
   ^
./GLImages.c:18:3: warning: incompatible implicit declaration of built-in function 'memcpy'
[armeabi-v7a] Install        : libjsc.so => /Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/build/exgl/all/armeabi-v7a/libjsc.so
[armeabi-v7a] Install        : libgnustl_shared.so => /Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/build/exgl/all/armeabi-v7a/libgnustl_shared.so
[x86] Compile++      : exgl <= EXGL.cpp
[x86] Compile++      : exgl <= GLImages.cpp
[x86] Compile        : exgl <= EXJSUtils.c
[x86] Compile        : exgl <= EXJSConvertTypedArray.c
./../../../../cpp/EXGL.cpp: In static member function 'static std::shared_ptr<char> EXGLContext::jsValueToSharedStr(JSContextRef, JSValueRef)':
./../../../../cpp/EXGL.cpp:253:87: error: 'free' was not declared in this scope
     return std::shared_ptr<char>(EXJSValueToUTF8CStringMalloc(jsCtx, jsVal, nullptr), free);
                                                                                       ^
[x86] Compile        : exgl <= EXGL.c
[x86] Compile        : exgl <= GLImages.c
./GLImages.c: In function 'Java_fr_greweb_rngl_GLImages_set':
./GLImages.c:18:3: warning: implicit declaration of function 'memcpy' [-Wimplicit-function-declaration]
   memcpy(data, bitmapPixels, size);
   ^
./GLImages.c:18:3: warning: incompatible implicit declaration of built-in function 'memcpy'
./../../../../cpp/EXGL.cpp: In member function 'std::shared_ptr<void> EXGLContext::jsValueToSharedArray(JSContextRef, JSValueRef, size_t*)':
./../../../../cpp/EXGL.cpp:346:82: error: 'free' was not declared in this scope
                                                                    pByteLength), free);
                                                                                  ^
./../../../../cpp/EXGL.cpp:362:43: error: 'malloc' was not declared in this scope
       void *dataMalloc = malloc(byteLength);
                                           ^
./../../../../cpp/EXGL.cpp:364:48: error: 'free' was not declared in this scope
       return std::shared_ptr<void>(dataMalloc, free);
                                                ^
./../../../../cpp/EXGL.cpp: In static member function 'static void EXGLContext::jsTypedArrayFreeDeallocator(void*, void*)':
./../../../../cpp/EXGL.cpp:369:14: error: 'free' was not declared in this scope
     free(data);
              ^
./../../../../cpp/EXGL.cpp: In member function 'const OpaqueJSValue* EXGLContext::makeTypedArray(JSContextRef, JSTypedArrayType, void*, size_t)':
./../../../../cpp/EXGL.cpp:378:45: error: 'malloc' was not declared in this scope
         void *dataMalloc = malloc(byteLength);
                                             ^
[x86] Install        : libjsc.so => /Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/build/exgl/all/x86/libjsc.so
[x86] Install        : libgnustl_shared.so => /Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/build/exgl/all/x86/libgnustl_shared.so
./../../../../cpp/EXGL.cpp: In static member function 'static std::shared_ptr<char> EXGLContext::jsValueToSharedStr(JSContextRef, JSValueRef)':
./../../../../cpp/EXGL.cpp:253:87: error: 'free' was not declared in this scope
     return std::shared_ptr<char>(EXJSValueToUTF8CStringMalloc(jsCtx, jsVal, nullptr), free);
                                                                                       ^
./../../../../cpp/EXGL.cpp: In member function 'std::shared_ptr<void> EXGLContext::jsValueToSharedArray(JSContextRef, JSValueRef, size_t*)':
./../../../../cpp/EXGL.cpp:346:82: error: 'free' was not declared in this scope
                                                                    pByteLength), free);
                                                                                  ^
./../../../../cpp/EXGL.cpp:362:43: error: 'malloc' was not declared in this scope
       void *dataMalloc = malloc(byteLength);
                                           ^
./../../../../cpp/EXGL.cpp:364:48: error: 'free' was not declared in this scope
       return std::shared_ptr<void>(dataMalloc, free);
                                                ^
./../../../../cpp/EXGL.cpp: In static member function 'static void EXGLContext::jsTypedArrayFreeDeallocator(void*, void*)':
./../../../../cpp/EXGL.cpp:369:14: error: 'free' was not declared in this scope
     free(data);
              ^
./../../../../cpp/EXGL.cpp: In member function 'const OpaqueJSValue* EXGLContext::makeTypedArray(JSContextRef, JSTypedArrayType, void*, size_t)':
./../../../../cpp/EXGL.cpp:378:45: error: 'malloc' was not declared in this scope
         void *dataMalloc = malloc(byteLength);
                                             ^
./../../../../cpp/EXGL.cpp: In member function 'const OpaqueJSValue* EXGLContext::exglNativeInstance_readPixels(JSContextRef, JSObjectRef, JSObjectRef, size_t, const OpaqueJSValue* const*, const OpaqueJSValue**)':
./../../../../cpp/EXGL.cpp:796:60: error: 'malloc' was not declared in this scope
       auto pixels = std::shared_ptr<void>(malloc(byteLength), free);
                                                            ^
./../../../../cpp/EXGL.cpp:796:63: error: 'free' was not declared in this scope
       auto pixels = std::shared_ptr<void>(malloc(byteLength), free);
                                                               ^
./../../../../cpp/EXGL.cpp: In member function 'const OpaqueJSValue* EXGLContext::exglNativeInstance_texImage2D(JSContextRef, JSObjectRef, JSObjectRef, size_t, const OpaqueJSValue* const*, const OpaqueJSValue**)':
./../../../../cpp/EXGL.cpp:934:34: error: 'malloc' was not declared in this scope
               data = malloc(bytes);
                                  ^
./../../../../cpp/EXGL.cpp: In member function 'const OpaqueJSValue* EXGLContext::exglNativeInstance_readPixels(JSContextRef, JSObjectRef, JSObjectRef, size_t, const OpaqueJSValue* const*, const OpaqueJSValue**)':
./../../../../cpp/EXGL.cpp:796:60: error: 'malloc' was not declared in this scope
       auto pixels = std::shared_ptr<void>(malloc(byteLength), free);
                                                            ^
./../../../../cpp/EXGL.cpp:796:63: error: 'free' was not declared in this scope
       auto pixels = std::shared_ptr<void>(malloc(byteLength), free);
                                                               ^
./../../../../cpp/EXGL.cpp: In member function 'const OpaqueJSValue* EXGLContext::exglNativeInstance_texImage2D(JSContextRef, JSObjectRef, JSObjectRef, size_t, const OpaqueJSValue* const*, const OpaqueJSValue**)':
./../../../../cpp/EXGL.cpp:934:34: error: 'malloc' was not declared in this scope
               data = malloc(bytes);
                                  ^
make: *** [/Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/build/tmp/buildEXGLLib/local/x86/objs/exgl/__/__/__/__/cpp/EXGL.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [/Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/build/tmp/buildEXGLLib/local/armeabi-v7a/objs/exgl/__/__/__/__/cpp/EXGL.o] Error 1
make: Leaving directory `/Users/fincher/Fincher/Develop/Front_End/Skylight-RN/SkylightRN/node_modules/gl-react-native/android/src/main/jni'
:gl-react-native:buildEXGLLib FAILED
```

**Comment by l-pa** [comment]
I am sorry, but I didn't fix this error, I decided to use Expo GL API, or solution for you can be v2, but for me with both (v2/v3) I still got this error .. :/

**Comment by songxiaoliang** [comment]
@Delfyn I have encountered this problem, how to solve it? We are expecting a reply

**Comment by l-pa** [comment]
@songxiaoliang I didnt solve it, try v3, or use Expo GLView
